<?php
$this->headTitle('Translations');

$this->mainMenu()->setActiveItemId('translations');

$this->pageBreadcrumbs()->setItems([
    $this->translator()->translate('home.text') => $this->url('home'),
    $this->translator()->translate('manage.languages') => $this->url('translators'),
    $this->translator()->translate('translator.new.index') => $this->url('translations', ['action' => 'add'])
]);
$form->setAttributes(array(
    'class' => 'form-horizontal',
    'enctype' => 'multipart/form-data'
));
?>
<h1><?php echo $this->translator()->translate('translator.head.title.add.index'); ?></h1>
<?php echo $this->form()->openTag($form); ?>
<?php
//Language form
echo $this->partial('translator/translation/partials/form.phtml', array('form' => $form));
?>
<div class="form-group row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <button type="submit" id="submit" class="btn btn-success"><?php echo $this->translator()->translate('save'); ?></button> 
        <a href="<?php echo $this->url('translations', ['action' => 'index']) ?>" class="btn btn-danger" title="<?php echo $this->translator()->translate('cancel'); ?>"><?php echo $this->translator()->translate('cancel'); ?></a>
    </div>  
</div>
<?php echo $this->form()->closeTag($form); ?>