<?php
$this->headTitle('Translators');

$this->mainMenu()->setActiveItemId('translators');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Manage Languages' => $this->url('beheer/translators'),
    'Edit Language' => $this->url('beheer/translators', ['action' => 'edit'])
]);
$form->setAttributes(array(
    'class' => 'form-horizontal',
    'enctype' => 'multipart/form-data'
));
?>
<h1>Manage Languages</h1>
<?php echo $this->form()->openTag($form); ?>
<?php
//Language form
echo $this->partial('translator/translator/partials/form.phtml', array('form' => $form));
?>
<div class="form-group row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <button type="submit" id="submit" class="btn btn-dark">Save</button> 
        <a href="<?php echo $this->url('beheer/translators') ?>" class="btn btn-danger" title="Annuleren">Cancel</a>
    </div>  
</div>
<?php echo $this->form()->closeTag($form); ?>