<?php
$this->headTitle('Languages');

$this->mainMenu()->setActiveItemId('languages');

$this->pageBreadcrumbs()->setItems([
    $this->translator()->translate('home.text') => $this->url('home'),
    $this->translator()->translate('manage.languages') => $this->url('languages'),
    $this->translator()->translate('language.edit') => $this->url('languages', ['action' => 'edit'])
]);
$form->setAttributes(array(
    'class' => 'form-horizontal',
    'enctype' => 'multipart/form-data'
));
?>
<h1><?php echo $this->translator()->translate('manage.languages'); ?></h1>
<?php echo $this->form()->openTag($form); ?>
<?php
//Language form
echo $this->partial('translator/language/partials/form.phtml', array('form' => $form, 'language' => $language));
?>
<!-- Image upload -->
<?php echo $this->partial('upload-images/partial/show_image.phtml', array('formImage' => $formImage, 'image' => $image, 'returnURL' => $returnURL)); ?>
<!-- End image upload -->
<div class="form-group row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <button type="submit" id="submit" class="btn btn-dark"><?php echo $this->translator()->translate('save'); ?></button>
        <a href="<?php echo $this->url('languages') ?>" class="btn btn-danger" title="<?php echo $this->translator()->translate('cancel'); ?>"><?php echo $this->translator()->translate('cancel'); ?></a>
    </div>  
</div>
<?php echo $this->form()->closeTag($form); ?>