<div class="col-lg-12 col-md-12 col-sm-12">
    <div class="form-group row">
        <?php echo $this->formLabel($form->get('name')); ?>
        <div class="col-sm-6 col-md-6 col-lg-6">
            <?php echo $this->formText($form->get('name')); ?>
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <?php echo (count($form->getMessages('name')) > 0 ? $form->getMessages('name')['isEmpty'] : '&nbsp;' ) ?>
        </div>
    </div>
    <div class="form-group row">
        <?php echo $this->formLabel($form->get('shortName')); ?>
        <div class="col-sm-6 col-md-6 col-lg-6">
            <?php echo $this->formText($form->get('shortName')); ?>
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <?php echo (count($form->getMessages('shortName')) > 0 ? $form->getMessages('shortName')['isEmpty'] : '&nbsp;' ) ?>
        </div>
    </div>
</div>