<?php
if (is_object($file)) {
    echo '<div id="file'.$file->getId().'">';
    echo '<img src="/' . $file->getPath() . '" alt="bla" width="250" height="auto" />';
    echo '<div class="fileOptions">';
    echo '  <span data-fileid="'.$file->getId() . '" class="btn btn-danger btn-sm deleteFileObject"><i class="fas fa-trash-alt"></i></span>';
    echo '</div>';
} else {
    ?>
    <div class="form-group <?php echo (count($form->getMessages('fileUpload')) > 0 ? 'has-error' : '' ) ?>">
        <label class="col-sm-4 col-md-4 col-lg-4 form-control-label">Upload flag</label>
        <div class="col-sm-6 col-md-6 col-lg-6">
            <div class="has-feedback">
                <div class="input-group">
                    <label class="input-group-addon btn btn-file">
                        Browse&hellip; <input type="file" name="fileUpload" style="display: none;" multiple>
                    </label>
                    <input type="text" class="form-control" name="fileUploadFileName" readonly>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group <?php echo (count($form->getMessages('fileDescription')) > 0 ? 'has-error' : '' ) ?>">
        <label class="col-sm-4 col-md-4 col-lg-4 form-control-label">File description</label>
        <div class="col-sm-6 col-md-6 col-lg-6">
            <?php echo $this->formText($form->get('fileDescription')); ?>
        </div>
    </div>
    <?php
}
?>
<hr />